// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Task_1.Models;

[Table("Department")]
[Index("ManagerHiredate", Name = "i_Hiredate")]
public partial class Department
{
    [Key]
    [Column("Dept_Id")]
    public int DeptId { get; set; }

    [Column("Dept_Name")]
    [StringLength(50)]
    public string DeptName { get; set; }

    [Column("Dept_Desc")]
    [StringLength(100)]
    public string DeptDesc { get; set; }

    [Column("Dept_Location")]
    [StringLength(50)]
    public string DeptLocation { get; set; }

    [Column("Dept_Manager")]
    public int? DeptManager { get; set; }

    [Column("Manager_hiredate", TypeName = "date")]
    public DateTime? ManagerHiredate { get; set; }

    [InverseProperty("Dept")]
    public virtual ICollection<Student> Students { get; } = new List<Student>();
}