// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;

namespace Task02.DAL.Models;

public partial class APID02Context : DbContext
{
    public APID02Context()
    {
    }

    public APID02Context(DbContextOptions<APID02Context> options)
        : base(options)
    {
    }

    public virtual DbSet<Departments> Departments { get; set; }

    public virtual DbSet<Developers> Developers { get; set; }

    public virtual DbSet<Tickets> Tickets { get; set; }

    protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        => optionsBuilder.UseSqlServer(@"Data Source=KHALED;Initial Catalog=APID02;Integrated Security=True;Connect Timeout=30;Encrypt=False;Trust Server Certificate=False;Application Intent=ReadWrite;MultiSubnetFailover=False");
                

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<Developers>(entity =>
        {
            entity.HasMany(d => d.Tickets).WithMany(p => p.Developers)
                .UsingEntity<Dictionary<string, object>>(
                    "DeveloperTicket",
                    r => r.HasOne<Tickets>().WithMany().HasForeignKey("TicketsId"),
                    l => l.HasOne<Developers>().WithMany().HasForeignKey("DevelopersId"),
                    j =>
                    {
                        j.HasKey("DevelopersId", "TicketsId");
                        j.HasIndex(new[] { "TicketsId" }, "IX_DeveloperTicket_TicketsId");
                    });
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}