// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Task02.DAL.Models;

[Index("DepartmentId", Name = "IX_Tickets_DepartmentId")]
public partial class Tickets
{
    [Key]
    public int Id { get; set; }

    [Required]
    public string Name { get; set; }

    public int DepartmentId { get; set; }

    [ForeignKey("DepartmentId")]
    [InverseProperty("Tickets")]
    public virtual Departments Department { get; set; }

    [ForeignKey("TicketsId")]
    [InverseProperty("Tickets")]
    public virtual ICollection<Developers> Developers { get; } = new List<Developers>();
}