//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVC_EF_43.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class City
    {
        public int cityID { get; set; }
        public string CityName { get; set; }
        public int cID { get; set; }
    
        public virtual Country Country { get; set; }
    }
}
