// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace NorthWindConsoleApp.Entities;

[Keyless]
public partial class SalesByCategory
{
    [Column("CategoryID")]
    public int CategoryId { get; set; }

    [Required]
    [StringLength(15)]
    public string CategoryName { get; set; }

    [Required]
    [StringLength(40)]
    public string ProductName { get; set; }

    [Column(TypeName = "money")]
    public decimal? ProductSales { get; set; }
}