// <auto-generated />
namespace Task.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class fix5 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(fix5));
        
        string IMigrationMetadata.Id
        {
            get { return "202303081739536_fix5"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
